input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # Add timestamp field
  mutate {
    add_field => { "[@metadata][timestamp]" => "%{+YYYY-MM-dd'T'HH:mm:ss.SSS'Z'}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "iot-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
